name: Windows build and tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - win-build

jobs:
  win-build:
    timeout-minutes: 30
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - name: start ursim
        run: |
          docker run alpine
        env:
          DOCKER_RUN_OPTS: --network ursim_net
          URSIM_VERSION: 'latest'
          ROBOT_MODEL: 'ur5e'
          PROGRAM_FOLDER: 'tests/resources/dockerursim/programs/e-series'
      - name: configure
        #run: mkdir build && cd build && cmake .. -DBUILDING_TESTS=1
        run: mkdir build && cd build && cmake .. -DBUILDING_TESTS=1 -DINTEGRATION_TESTS=1
      - name: build
        run: cmake --build build --config Debug
      - name: test
        run: cd build && ctest --output-on-failure -C Debug
      - name: run examples
        run: ./run_examples.sh "192.168.56.101" 1
